// <auto-generated />
using System;
using Finama.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finama.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finama.Core.Entities.AppareilConfiance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDerniereValidation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId", "DeviceId")
                        .IsUnique();

                    b.ToTable("AppareilsConfiance", (string)null);
                });

            modelBuilder.Entity("Finama.Core.Entities.ClasseComptable", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TenantId", "Numero");

                    b.ToTable("ClassesComptables", (string)null);
                });

            modelBuilder.Entity("Finama.Core.Entities.CompteComptable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Classe")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CompteParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSysteme")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompteParentId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("CompteComptables");
                });

            modelBuilder.Entity("Finama.Core.Entities.Devise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("TauxBaseDollar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Devises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 5, 30, 13, 26, 52, 421, DateTimeKind.Utc).AddTicks(1794),
                            DateMiseAJour = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EstActive = true,
                            IsDeleted = false,
                            Libelle = "Dollar américain",
                            Symbole = "$",
                            TauxBaseDollar = 1.0000m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "XOF",
                            CreatedAt = new DateTime(2026, 5, 30, 13, 26, 52, 431, DateTimeKind.Utc).AddTicks(6465),
                            DateMiseAJour = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EstActive = true,
                            IsDeleted = false,
                            Libelle = "Franc CFA (BCEAO)",
                            Symbole = "FCFA",
                            TauxBaseDollar = 615.0000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 5, 30, 13, 26, 52, 431, DateTimeKind.Utc).AddTicks(6598),
                            DateMiseAJour = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EstActive = true,
                            IsDeleted = false,
                            Libelle = "Euro",
                            Symbole = "€",
                            TauxBaseDollar = 0.9200m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "GHS",
                            CreatedAt = new DateTime(2026, 5, 30, 13, 26, 52, 431, DateTimeKind.Utc).AddTicks(6616),
                            DateMiseAJour = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EstActive = true,
                            IsDeleted = false,
                            Libelle = "Cedi ghanéen",
                            Symbole = "₵",
                            TauxBaseDollar = 14.5000m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "NGN",
                            CreatedAt = new DateTime(2026, 5, 30, 13, 26, 52, 431, DateTimeKind.Utc).AddTicks(6626),
                            DateMiseAJour = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EstActive = true,
                            IsDeleted = false,
                            Libelle = "Naira nigérian",
                            Symbole = "₦",
                            TauxBaseDollar = 1490.0000m
                        });
                });

            modelBuilder.Entity("Finama.Core.Entities.EcritureComptable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateEcriture")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ExerciceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FactureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("FactureId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique();

                    b.ToTable("Ecritures");
                });

            modelBuilder.Entity("Finama.Core.Entities.ExerciceComptable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClotureLe")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Finama.Core.Entities.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateEcheance")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontantRegle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TiersId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TiersId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneEcriture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("EcritureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .HasColumnType("text");

                    b.Property<decimal?>("MontantDeviseBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TauxChange")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TiersId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.HasIndex("EcritureId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TiersId");

                    b.ToTable("LignesEcriture");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneFacture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompteProduitsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FactureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompteProduitsId");

                    b.HasIndex("FactureId");

                    b.HasIndex("TenantId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("Finama.Core.Entities.PaysConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeFiscal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeISO")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviseCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DeviseSymbole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TauxTVAStandard")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeISO")
                        .IsUnique();

                    b.HasIndex("DeviseCode");

                    b.ToTable("Pays");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CodeFiscal = "NIF",
                            CodeISO = "TG",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Togo",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CodeFiscal = "NIF",
                            CodeISO = "ST",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "STD",
                            DeviseSymbole = "Db",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "pt",
                            Nom = "São Tomé et Príncipe",
                            TauxTVAStandard = 15m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CodeFiscal = "NINEA",
                            CodeISO = "SN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Sénégal",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CodeFiscal = "DGI",
                            CodeISO = "CI",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Côte d'Ivoire",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CodeFiscal = "IFU",
                            CodeISO = "BJ",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Bénin",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CodeFiscal = "IFU",
                            CodeISO = "BF",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Burkina Faso",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CodeFiscal = "NIF",
                            CodeISO = "ML",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Mali",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CodeFiscal = "NIF",
                            CodeISO = "NE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XOF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Niger",
                            TauxTVAStandard = 19m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CodeFiscal = "NIU",
                            CodeISO = "CM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XAF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Cameroun",
                            TauxTVAStandard = 19.25m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CodeFiscal = "NIF",
                            CodeISO = "GA",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XAF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Gabon",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CodeFiscal = "NIU",
                            CodeISO = "CG",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "XAF",
                            DeviseSymbole = "FCFA",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Congo",
                            TauxTVAStandard = 18m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CodeFiscal = "NIF",
                            CodeISO = "GN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviseCode = "GNF",
                            DeviseSymbole = "FG",
                            EstActif = true,
                            IsDeleted = false,
                            Langue = "fr",
                            Nom = "Guinée",
                            TauxTVAStandard = 18m
                        });
                });

            modelBuilder.Entity("Finama.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AbonnementExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<bool>("AssujettTVA")
                        .HasColumnType("boolean");

                    b.Property<string>("BanqueBIC")
                        .HasColumnType("text");

                    b.Property<string>("BanqueNom")
                        .HasColumnType("text");

                    b.Property<string>("BanqueRIB")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviseBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroFiscal")
                        .HasColumnType("text");

                    b.Property<Guid>("PaysId")
                        .HasColumnType("uuid");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("PlanComptableCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlugUnique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaysId");

                    b.HasIndex("SlugUnique")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tiers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompteComptableId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Devise")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NINEA")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompteComptableId");

                    b.HasIndex("TenantId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Finama.Core.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DerniereConnexionAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOtpValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpireAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Finama.Core.Entities.AppareilConfiance", b =>
                {
                    b.HasOne("Finama.Core.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Finama.Core.Entities.ClasseComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.CompteComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "CompteParent")
                        .WithMany("SousComptes")
                        .HasForeignKey("CompteParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("CompteComptables")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompteParent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.EcritureComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.ExerciceComptable", "Exercice")
                        .WithMany("Ecritures")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Facture", "Facture")
                        .WithMany("Ecritures")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Ecritures")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Facture");

                    b.Navigation("Tenant");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Finama.Core.Entities.ExerciceComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Exercices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.Facture", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Factures")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tiers", "Tiers")
                        .WithMany("Factures")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneEcriture", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "Compte")
                        .WithMany("Lignes")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.EcritureComptable", "Ecriture")
                        .WithMany("Lignes")
                        .HasForeignKey("EcritureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tiers", "Tiers")
                        .WithMany("Lignes")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Compte");

                    b.Navigation("Ecriture");

                    b.Navigation("Tenant");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneFacture", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "CompteProduits")
                        .WithMany()
                        .HasForeignKey("CompteProduitsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompteProduits");

                    b.Navigation("Facture");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tenant", b =>
                {
                    b.HasOne("Finama.Core.Entities.PaysConfig", "Pays")
                        .WithMany("Tenants")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tiers", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "CompteComptable")
                        .WithMany()
                        .HasForeignKey("CompteComptableId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Tiers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompteComptable");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.Utilisateur", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.CompteComptable", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("SousComptes");
                });

            modelBuilder.Entity("Finama.Core.Entities.EcritureComptable", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Finama.Core.Entities.ExerciceComptable", b =>
                {
                    b.Navigation("Ecritures");
                });

            modelBuilder.Entity("Finama.Core.Entities.Facture", b =>
                {
                    b.Navigation("Ecritures");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Finama.Core.Entities.PaysConfig", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tenant", b =>
                {
                    b.Navigation("CompteComptables");

                    b.Navigation("Ecritures");

                    b.Navigation("Exercices");

                    b.Navigation("Factures");

                    b.Navigation("Tiers");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tiers", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
