// <auto-generated />
using System;
using Finama.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finama.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502130804_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finama.Core.Entities.CompteComptable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<Guid?>("CompteParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSysteme")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompteParentId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("CompteComptables");
                });

            modelBuilder.Entity("Finama.Core.Entities.EcritureComptable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEcriture")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FactureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Journal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("FactureId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("TenantId", "Reference")
                        .IsUnique();

                    b.ToTable("Ecritures");
                });

            modelBuilder.Entity("Finama.Core.Entities.ExerciceComptable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClotureLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstCloture")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Finama.Core.Entities.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantRegle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TiersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TiersId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneEcriture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("EcritureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontantDeviseBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TauxChange")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TiersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.HasIndex("EcritureId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TiersId");

                    b.ToTable("LignesEcriture");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneFacture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompteProduitsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FactureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompteProduitsId");

                    b.HasIndex("FactureId");

                    b.HasIndex("TenantId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AbonnementExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviseBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NINEA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<string>("PlanComptableCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlugUnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SlugUnique")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tiers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CompteComptableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Devise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NINEA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompteComptableId");

                    b.HasIndex("TenantId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("Finama.Core.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DerniereConnexionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Finama.Core.Entities.CompteComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "CompteParent")
                        .WithMany("SousComptes")
                        .HasForeignKey("CompteParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("CompteComptables")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompteParent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.EcritureComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.ExerciceComptable", "Exercice")
                        .WithMany("Ecritures")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Facture", "Facture")
                        .WithMany("Ecritures")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Ecritures")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Facture");

                    b.Navigation("Tenant");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Finama.Core.Entities.ExerciceComptable", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Exercices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.Facture", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Factures")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tiers", "Tiers")
                        .WithMany("Factures")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneEcriture", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "Compte")
                        .WithMany("Lignes")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.EcritureComptable", "Ecriture")
                        .WithMany("Lignes")
                        .HasForeignKey("EcritureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tiers", "Tiers")
                        .WithMany("Lignes")
                        .HasForeignKey("TiersId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Compte");

                    b.Navigation("Ecriture");

                    b.Navigation("Tenant");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Finama.Core.Entities.LigneFacture", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "CompteProduits")
                        .WithMany()
                        .HasForeignKey("CompteProduitsId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompteProduits");

                    b.Navigation("Facture");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tiers", b =>
                {
                    b.HasOne("Finama.Core.Entities.CompteComptable", "CompteComptable")
                        .WithMany()
                        .HasForeignKey("CompteComptableId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Tiers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompteComptable");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.Utilisateur", b =>
                {
                    b.HasOne("Finama.Core.Entities.Tenant", "Tenant")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Finama.Core.Entities.CompteComptable", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("SousComptes");
                });

            modelBuilder.Entity("Finama.Core.Entities.EcritureComptable", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Finama.Core.Entities.ExerciceComptable", b =>
                {
                    b.Navigation("Ecritures");
                });

            modelBuilder.Entity("Finama.Core.Entities.Facture", b =>
                {
                    b.Navigation("Ecritures");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tenant", b =>
                {
                    b.Navigation("CompteComptables");

                    b.Navigation("Ecritures");

                    b.Navigation("Exercices");

                    b.Navigation("Factures");

                    b.Navigation("Tiers");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Finama.Core.Entities.Tiers", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
